HEADERS += eigen/Eigen/LU \
    eigen/Eigen/QR \
    eigen/Eigen/SVD \
    eigen/Eigen/src/LU/arch/Inverse_SSE.h \
    eigen/Eigen/src/LU/PartialPivLU.h \
    eigen/Eigen/src/LU/Inverse.h \
    eigen/Eigen/src/LU/Determinant.h \
    eigen/Eigen/src/LU/FullPivLU.h \
    eigen/Eigen/src/QR/HouseholderQR.h \
    eigen/Eigen/src/QR/ColPivHouseholderQR.h \
    eigen/Eigen/src/QR/FullPivHouseholderQR.h \
    eigen/Eigen/src/SVD/JacobiSVD.h \
    eigen/Eigen/src/SVD/UpperBidiagonalization.h \
    eigen/Eigen/src/Core/IO.h \
    eigen/Eigen/src/Core/arch/SSE/PacketMath.h \
    eigen/Eigen/src/Core/arch/SSE/MathFunctions.h \
    eigen/Eigen/src/Core/arch/SSE/Complex.h \
    eigen/Eigen/src/Core/arch/NEON/PacketMath.h \
    eigen/Eigen/src/Core/arch/NEON/Complex.h \
    eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    eigen/Eigen/src/Core/arch/AltiVec/Complex.h \
    eigen/Eigen/src/Core/arch/Default/Settings.h \
    eigen/Eigen/src/Core/util/StaticAssert.h \
    eigen/Eigen/src/Core/util/Meta.h \
    eigen/Eigen/src/Core/util/BlasUtil.h \
    eigen/Eigen/src/Core/util/ForwardDeclarations.h \
    eigen/Eigen/src/Core/util/ReenableStupidWarnings.h \
    eigen/Eigen/src/Core/util/DisableStupidWarnings.h \
    eigen/Eigen/src/Core/util/Memory.h \
    eigen/Eigen/src/Core/util/Constants.h \
    eigen/Eigen/src/Core/util/XprHelper.h \
    eigen/Eigen/src/Core/util/Macros.h \
    eigen/Eigen/src/Core/VectorwiseOp.h \
    eigen/Eigen/src/Core/SolveTriangular.h \
    eigen/Eigen/src/Core/StableNorm.h \
    eigen/Eigen/src/Core/SelfAdjointView.h \
    eigen/Eigen/src/Core/Dot.h \
    eigen/Eigen/src/Core/Map.h \
    eigen/Eigen/src/Core/TriangularMatrix.h \
    eigen/Eigen/src/Core/Array.h \
    eigen/Eigen/src/Core/DiagonalProduct.h \
    eigen/Eigen/src/Core/DenseStorage.h \
    eigen/Eigen/src/Core/SelfCwiseBinaryOp.h \
    eigen/Eigen/src/Core/DiagonalMatrix.h \
    eigen/Eigen/src/Core/NestByValue.h \
    eigen/Eigen/src/Core/Random.h \
    eigen/Eigen/src/Core/Block.h \
    eigen/Eigen/src/Core/Matrix.h \
    eigen/Eigen/src/Core/VectorBlock.h \
    eigen/Eigen/src/Core/BooleanRedux.h \
    eigen/Eigen/src/Core/Swap.h \
    eigen/Eigen/src/Core/CwiseUnaryView.h \
    eigen/Eigen/src/Core/Functors.h \
    eigen/Eigen/src/Core/PermutationMatrix.h \
    eigen/Eigen/src/Core/GenericPacketMath.h \
    eigen/Eigen/src/Core/Select.h \
    eigen/Eigen/src/Core/Product.h \
    eigen/Eigen/src/Core/DenseBase.h \
    eigen/Eigen/src/Core/PlainObjectBase.h \
    eigen/Eigen/src/Core/BandMatrix.h \
    eigen/Eigen/src/Core/Redux.h \
    eigen/Eigen/src/Core/Replicate.h \
    eigen/Eigen/src/Core/CwiseNullaryOp.h \
    eigen/Eigen/src/Core/Transpose.h \
    eigen/Eigen/src/Core/CommaInitializer.h \
    eigen/Eigen/src/Core/ProductBase.h \
    eigen/Eigen/src/Core/Diagonal.h \
    eigen/Eigen/src/Core/Stride.h \
    eigen/Eigen/src/Core/NoAlias.h \
    eigen/Eigen/src/Core/ForceAlignedAccess.h \
    eigen/Eigen/src/Core/Assign.h \
    eigen/Eigen/src/Core/MathFunctions.h \
    eigen/Eigen/src/Core/Reverse.h \
    eigen/Eigen/src/Core/DenseCoeffsBase.h \
    eigen/Eigen/src/Core/CwiseUnaryOp.h \
    eigen/Eigen/src/Core/GlobalFunctions.h \
    eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    eigen/Eigen/src/Core/products/Parallelizer.h \
    eigen/Eigen/src/Core/products/TriangularSolverMatrix.h \
    eigen/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    eigen/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    eigen/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    eigen/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    eigen/Eigen/src/Core/products/SelfadjointProduct.h \
    eigen/Eigen/src/Core/products/SelfadjointRank2Update.h \
    eigen/Eigen/src/Core/products/CoeffBasedProduct.h \
    eigen/Eigen/src/Core/products/TriangularSolverVector.h \
    eigen/Eigen/src/Core/products/TriangularMatrixVector.h \
    eigen/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    eigen/Eigen/src/Core/products/GeneralMatrixVector.h \
    eigen/Eigen/src/Core/NumTraits.h \
    eigen/Eigen/src/Core/ReturnByValue.h \
    eigen/Eigen/src/Core/MatrixBase.h \
    eigen/Eigen/src/Core/Flagged.h \
    eigen/Eigen/src/Core/ArrayBase.h \
    eigen/Eigen/src/Core/Transpositions.h \
    eigen/Eigen/src/Core/Fuzzy.h \
    eigen/Eigen/src/Core/ArrayWrapper.h \
    eigen/Eigen/src/Core/Visitor.h \
    eigen/Eigen/src/Core/EigenBase.h \
    eigen/Eigen/src/Core/CwiseBinaryOp.h \
    eigen/Eigen/src/Core/MapBase.h \
    eigen/Eigen/src/misc/Image.h \
    eigen/Eigen/src/misc/Kernel.h \
    eigen/Eigen/src/misc/Solve.h \
    eigen/Eigen/src/Eigen2Support/LU.h \
    eigen/Eigen/src/Eigen2Support/QR.h \
    eigen/Eigen/src/Eigen2Support/SVD.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Quaternion.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Scaling.h \
    eigen/Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
    eigen/Eigen/src/Eigen2Support/Geometry/All.h \
    eigen/Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
    eigen/Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
    eigen/Eigen/src/Eigen2Support/Geometry/RotationBase.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Transform.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
    eigen/Eigen/src/Eigen2Support/Geometry/Translation.h \
    eigen/Eigen/src/Eigen2Support/Lazy.h \
    eigen/Eigen/src/Eigen2Support/Meta.h \
    eigen/Eigen/src/Eigen2Support/Block.h \
    eigen/Eigen/src/Eigen2Support/VectorBlock.h \
    eigen/Eigen/src/Eigen2Support/LeastSquares.h \
    eigen/Eigen/src/Eigen2Support/Cwise.h \
    eigen/Eigen/src/Eigen2Support/MathFunctions.h \
    eigen/Eigen/src/Eigen2Support/Memory.h \
    eigen/Eigen/src/Eigen2Support/TriangularSolver.h \
    eigen/Eigen/src/Eigen2Support/CwiseOperators.h \
    eigen/Eigen/src/Eigen2Support/Minor.h \
    eigen/Eigen/src/Eigen2Support/Macros.h \
    eigen/Eigen/src/Jacobi/Jacobi.h \
    eigen/Eigen/src/Geometry/arch/Geometry_SSE.h \
    eigen/Eigen/src/Geometry/Quaternion.h \
    eigen/Eigen/src/Geometry/Scaling.h \
    eigen/Eigen/src/Geometry/AlignedBox.h \
    eigen/Eigen/src/Geometry/OrthoMethods.h \
    eigen/Eigen/src/Geometry/AngleAxis.h \
    eigen/Eigen/src/Geometry/Hyperplane.h \
    eigen/Eigen/src/Geometry/ParametrizedLine.h \
    eigen/Eigen/src/Geometry/RotationBase.h \
    eigen/Eigen/src/Geometry/Transform.h \
    eigen/Eigen/src/Geometry/Rotation2D.h \
    eigen/Eigen/src/Geometry/EulerAngles.h \
    eigen/Eigen/src/Geometry/Translation.h \
    eigen/Eigen/src/Geometry/Umeyama.h \
    eigen/Eigen/src/Geometry/Homogeneous.h \
    eigen/Eigen/src/Cholesky/LDLT.h \
    eigen/Eigen/src/Cholesky/LLT.h \
    eigen/Eigen/src/Sparse/SparseProduct.h \
    eigen/Eigen/src/Sparse/SparseCwiseUnaryOp.h \
    eigen/Eigen/src/Sparse/SparseAssign.h \
    eigen/Eigen/src/Sparse/SparseTranspose.h \
    eigen/Eigen/src/Sparse/DynamicSparseMatrix.h \
    eigen/Eigen/src/Sparse/SparseFuzzy.h \
    eigen/Eigen/src/Sparse/SparseDenseProduct.h \
    eigen/Eigen/src/Sparse/SparseDot.h \
    eigen/Eigen/src/Sparse/SparseVector.h \
    eigen/Eigen/src/Sparse/SparseView.h \
    eigen/Eigen/src/Sparse/SparseUtil.h \
    eigen/Eigen/src/Sparse/SparseBlock.h \
    eigen/Eigen/src/Sparse/SparseSelfAdjointView.h \
    eigen/Eigen/src/Sparse/TriangularSolver.h \
    eigen/Eigen/src/Sparse/SparseCwiseBinaryOp.h \
    eigen/Eigen/src/Sparse/SparseTriangularView.h \
    eigen/Eigen/src/Sparse/SparseDiagonalProduct.h \
    eigen/Eigen/src/Sparse/SparseMatrix.h \
    eigen/Eigen/src/Sparse/AmbiVector.h \
    eigen/Eigen/src/Sparse/SparseSparseProduct.h \
    eigen/Eigen/src/Sparse/CoreIterators.h \
    eigen/Eigen/src/Sparse/SparseMatrixBase.h \
    eigen/Eigen/src/Sparse/SparseRedux.h \
    eigen/Eigen/src/Sparse/CompressedStorage.h \
    eigen/Eigen/src/Sparse/MappedSparseMatrix.h \
    eigen/Eigen/src/Householder/BlockHouseholder.h \
    eigen/Eigen/src/Householder/HouseholderSequence.h \
    eigen/Eigen/src/Householder/Householder.h \
    eigen/Eigen/src/StlSupport/StdList.h \
    eigen/Eigen/src/StlSupport/StdDeque.h \
    eigen/Eigen/src/StlSupport/StdVector.h \
    eigen/Eigen/src/StlSupport/details.h \
    eigen/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    eigen/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    eigen/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    eigen/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    eigen/Eigen/src/Eigenvalues/RealSchur.h \
    eigen/Eigen/src/Eigenvalues/ComplexSchur.h \
    eigen/Eigen/src/Eigenvalues/Tridiagonalization.h \
    eigen/Eigen/src/Eigenvalues/EigenSolver.h \
    eigen/Eigen/src/Eigenvalues/EigenvaluesCommon.h \
    eigen/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    eigen/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    eigen/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    eigen/Eigen/src/plugins/BlockMethods.h \
    eigen/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    eigen/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    eigen/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    eigen/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    eigen/Eigen/Core \
    eigen/Eigen/Array \
    eigen/Eigen/Dense \
    eigen/Eigen/Eigen \
    eigen/Eigen/Eigen2Support \
    eigen/Eigen/Jacobi \
    eigen/Eigen/Geometry \
    eigen/Eigen/Cholesky \
    eigen/Eigen/Sparse \
    eigen/Eigen/StdDeque \
    eigen/Eigen/LeastSquares \
    eigen/Eigen/Householder \
    eigen/Eigen/StdVector \
    eigen/Eigen/QtAlignedMalloc \
    eigen/Eigen/Eigenvalues \
    eigen/Eigen/StdList \
    eigen/unsupported/Eigen/BVH \
    eigen/unsupported/Eigen/FFT \
    eigen/unsupported/Eigen/src/BVH/KdBVH.h \
    eigen/unsupported/Eigen/src/BVH/BVAlgorithms.h \
    eigen/unsupported/Eigen/src/FFT/ei_fftw_impl.h \
    eigen/unsupported/Eigen/src/FFT/ei_kissfft_impl.h \
    eigen/unsupported/Eigen/src/NumericalDiff/NumericalDiff.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixFunction.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixFunctionAtomic.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/StemFunction.h \
    eigen/unsupported/Eigen/src/MatrixFunctions/MatrixExponential.h \
    eigen/unsupported/Eigen/src/SparseExtra/Amd.h \
    eigen/unsupported/Eigen/src/SparseExtra/SparseLU.h \
    eigen/unsupported/Eigen/src/SparseExtra/CholmodSupport.h \
    eigen/unsupported/Eigen/src/SparseExtra/CholmodSupportLegacy.h \
    eigen/unsupported/Eigen/src/SparseExtra/RandomSetter.h \
    eigen/unsupported/Eigen/src/SparseExtra/SparseLDLTLegacy.h \
    eigen/unsupported/Eigen/src/SparseExtra/SparseLLT.h \
    eigen/unsupported/Eigen/src/SparseExtra/SimplicialCholesky.h \
    eigen/unsupported/Eigen/src/SparseExtra/Solve.h \
    eigen/unsupported/Eigen/src/SparseExtra/UmfPackSupport.h \
    eigen/unsupported/Eigen/src/SparseExtra/SuperLUSupport.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineUtil.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineMatrix.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineMatrixBase.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineProduct.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineInplaceLU.h \
    eigen/unsupported/Eigen/src/Skyline/SkylineStorage.h \
    eigen/unsupported/Eigen/src/Polynomials/PolynomialUtils.h \
    eigen/unsupported/Eigen/src/Polynomials/Companion.h \
    eigen/unsupported/Eigen/src/Polynomials/PolynomialSolver.h \
    eigen/unsupported/Eigen/src/AutoDiff/AutoDiffJacobian.h \
    eigen/unsupported/Eigen/src/AutoDiff/AutoDiffScalar.h \
    eigen/unsupported/Eigen/src/AutoDiff/AutoDiffVector.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/IterationController.h \
    eigen/unsupported/Eigen/src/IterativeSolvers/ConstrainedConjGrad.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/covar.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/LevenbergMarquardt.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/lmpar.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/chkder.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/qrsolv.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/r1mpyq.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/HybridNonLinearSolver.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/r1updt.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/fdjac1.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/rwupdt.h \
    eigen/unsupported/Eigen/src/NonLinearOptimization/dogleg.h \
    eigen/unsupported/Eigen/src/MoreVectorization/MathFunctions.h \
    eigen/unsupported/Eigen/MPRealSupport \
    eigen/unsupported/Eigen/NumericalDiff \
    eigen/unsupported/Eigen/MatrixFunctions \
    eigen/unsupported/Eigen/AlignedVector3 \
    eigen/unsupported/Eigen/CholmodSupport \
    eigen/unsupported/Eigen/SparseExtra \
    eigen/unsupported/Eigen/AdolcForward \
    eigen/unsupported/Eigen/Skyline \
    eigen/unsupported/Eigen/UmfPackSupport \
    eigen/unsupported/Eigen/OpenGLSupport \
    eigen/unsupported/Eigen/Polynomials \
    eigen/unsupported/Eigen/AutoDiff \
    eigen/unsupported/Eigen/IterativeSolvers \
    eigen/unsupported/Eigen/SuperLUSupport \
    eigen/unsupported/Eigen/NonLinearOptimization \
    eigen/unsupported/Eigen/MoreVectorization
